#!/bin/sh
#
# Starts Weston
#

# HACK!
export XDG_RUNTIME_DIR=/temp
mkdir -p $XDG_RUNTIME_DIR
chmod 700 $XDG_RUNTIME_DIR

BIN=/usr/bin/weston
PIDFILE=/var/run/weston.pid

# start weston on 1st tty
# with kiosk shell
WESTON_ARGS="--tty=1 --shell=kiosk-shell.so"

start() {
	printf "Starting Weston: "
	start-stop-daemon -S -q -b -m -p $PIDFILE --exec $BIN -- $WESTON_ARGS
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping Weston: "
	start-stop-daemon -K -q -p $PIDFILE
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
	stop
	sleep 2
	start
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart|reload)
		restart
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

