#!/bin/sh
#
# Starts Rinputer2
#

BIN=/bin/rinputer2
PIDFILE=/var/run/rinputer2.pid

start() {
	printf "Starting Rinputer2: "
	start-stop-daemon -S -q -b -m -p $PIDFILE --exec $BIN
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping Rinputer2: "
	start-stop-daemon -K -q -p $PIDFILE
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
	stop
	sleep 2
	start
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart|reload)
		restart
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

